server:
  port: 8081
  servlet:
    context-path: /Z-blogs
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql:///z-blogs?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true


jwt:
  header: Authorization
  secretKey: Z-blogs
  bearer: "Bearer "
  expiration: 43200000